version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      sub-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major:
        patterns:
          - "*"
        update-types:
          - major
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      sub-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major:
        patterns:
          - "*"
        update-types:
          - major
